name: Build and Release All Destinations

on:
  push:
  #   tags:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v0.0.0'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release XCFramework
    runs-on: macos-15
    # if: github.ref_type == 'tag'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          brew install go

      - name: Determine Tag
        id: tag
        run: |
          INPUT_TAG=${{ github.event.inputs.version }}
          DATE=$(date -Idate -Iseconds | perl -pe 's/T/_/' | perl -pe 's/[^0-9\s_]/-/g')

          if [[ -n $INPUT_TAG ]]; then
            OUT=$INPUT_TAG
          else
            OUT=$DATE
          fi

          echo "TAG=$OUT" >> "${GITHUB_OUTPUT}"

      - name: Build XCFramework
        run: |
          set -xoe

          pushd WireGuardGoFoundationSource
          make build-xcframework

          zip -ry WireGuardGoFoundation.xcframework.zip WireGuardGoFoundation.xcframework
          popd
          mv WireGuardGoFoundationSource/WireGuardGoFoundation.xcframework.zip .

      - name: Update Package
        run: |
          set -xoe

          CHECKSUM=$(swift package compute-checksum WireGuardGoFoundation.xcframework.zip)
          NEW_URL="https://github.com/${{ github.repository_owner }}/WGTest/releases/download/${TAG}/WireGuardGoFoundation.xcframework.zip"

          sed -i "" "s|let url = \".*\"|let url = \"$NEW_URL\"|" Package.swift
          sed -i "" "s|let checksum = \".*\"|let checksum = \"$CHECKSUM\"|" Package.swift

          git add Package.swift
          git commit -m "Release ${TAG}"
          git push
          git tag ${TAG}
          git push origin ${TAG}
        env:
          TAG: ${{ steps.tag.outputs.TAG }}


      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: WireGuardGoFoundation.xcframework.zip
          make_latest: true
          target_commitish: ${{ steps.tag.outputs.TAG }}
          tag_name: ${{ steps.tag.outputs.TAG }}
